resources:
  repositories:
  - repository: templates
    type: git
    name: Devops-Corporativo/templates-ci
    ref: feature/newPipeWorkflow 

trigger:
- '*'

stages:
- template: pipeline.yaml@templates
  parameters:
    BuildType: Container
    PathDockerfile: Dockerfile
    Veracode: No
    noCode: true
