projectName: app-teste
namespace: "deploy-teste"
dockerRegistry: openshift-image-registry.apps.dev.corp.btb
replicas:
  min: 1
  max: 2
containerPort: 8080
hostSuffix: apps.dev.corp.btb
commonLabels: {}
commonAnnotations: {}
nodeSelector: {}
livenessProbe:
  enabled: true
  type: httpGet
  path: /

readinessProbe:
  enabled: true
  type: httpGet
  path: /

resources:
  limits:
    cpu: 150m
    memory: 256Mi
  requests:
    cpu: 20m
    memory: 64Mi

secrets:
#  - name: SECURITY_OAUTH2_USERNAME
#    secretKeyRef:
#      key: SECURITY_OAUTH2_USERNAME
#      name: username
#  - name: SECURITY_OAUTH2_PASSWORD
#    secretKeyRef:
#      key: SECURITY_OAUTH2_PASSWORD
#      name: pwd-api

environment:
  - name: TARGET_PORT
    value: '8080'
  - name: STAGE
    value: 'HML'
  - name: BACKGROUND_COLOR
    value: green
  - name: ENABLE_BUTTON
    value: true
  - name: MENSAGEM
    value: "Aplicação de testes! v2"

metrics:
  cpu:
    enabled: true
    averageUtilization: 80
  memory:
    enabled: false
    averageUtilization: 80

enableHPA: true
enableDeployment: true
enableRoute: true
enableService: true
enableImageStream: false

apiVersions:
  hpa: autoscaling/v2
  deploymentConfig: apps.openshift.io/v1
  route: route.openshift.io/v1
  service: v1

enablePVC: false
VolumePersistence:
# Valores de nome de volume e pvc padrão (projectName)
#  - mountPath: /mnt/arquivos
#    size: 128Mi
# Definindo valores customizados
#  - name: app-name # Nome do pvc
#    mountPath: /mnt/arquivos
#    storageClassName: ocs-storagecluster-cephfs
#    volName: volume-5pcuk
#    size: 1G
#    volMode: Filesystem
#    ReadWriteMany: ReadWriteMany
#
# Caso a aplicação use empty Dir
enableEmptyDir: false
emptyDir:
#  - name: redis-1
#    mountPath: /data
#
strategy:
  type: Rolling
#  rollingParams:
#    intervalSeconds: 1
#    maxSurge: 50%
#    maxUnavailable: 50%
#    timeoutSeconds: 6000
#    updatePeriodSeconds: 1

#securityContext:
#  enabled: true
#  capabilities:
#    add: ["NET_BIND_SERVICE"]

